before_install:
  - sudo apt-get update

language: r
cache: packages

r_packages:
  - DiagrammeR
  - lattice 
  - roxygen2
  - protViz
  - shiny
  - testthat
  - knitr
  - rmarkdown
warnings_are_errors: false
